dataset:
  name: "NYUDepthv2"
  root: "data/NYUDepthv2"
  n_classes: 40
  ignore_index: 255
  train_split: "train"
  val_split: "test"

transforms:
  base_size: 520
  crop_size: 480
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

loader:
  batch_size: 4  # 单卡 batch size
  num_workers: 4
  pin_memory: True